### ISSUE TITLE
Can't get it to sync to beats

### ISSUE THREAD

**Issue by dandv** [njm222/Spotify_Visualizer#7]
I'm playing Queen - We Will Rock You, which has some obvious beats, but the animations aren't in sync. I've granted microphone permission... what am I doing wrong?

**Comment by njm222** [comment]
@dandv 

Short answer: 
you aren't doing anything wrong.

The beats of a track are obtained through the Spotify API audio analysis [endpoint](https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-analysis/), however not all the beats are used in the visualization, only beats with a confidence greater than the (mean - _x_ standard deviations away from the mean) are used.

Are the visuals moving \ can you see colours changing on all the modes?
Can you open up the console to see if there are any errors popping up?
Is it just _Queen - We Will Rock You_ that you are having an issue with?

If this is not repeatable, then the issue was on Spotify's API which goes down sometimes, I will add in user alerts for when the service goes offline.
